/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Vm {
  constructor()
  run(source: string): string
  registerModule(name: string, source: string): void
  setImportMetaMain(isMain: boolean): void
  /**
   * Cap the number of loop iterations a single execution may perform
   * (default 100M). When the budget runs out, the VM throws a catchable
   * `RangeError` instead of freezing the host event loop forever.
   */
  setLoopLimit(n: number): void
  getGlobal(name: string): string
  /**
   * Define a global variable in the VM from a structured Node value. The
   * value is reachable both as a bare identifier and (once the global
   * aliases are wired) via `window`/`globalThis`/`self`.
   */
  setGlobal(name: string, value: unknown): void
  /**
   * Expose a Node function to the VM as a global. VM code can then call it
   * by name; arguments and the return value are marshalled across the
   * boundary, and a thrown error propagates into the VM as a catchable
   * exception.
   */
  exposeFunction(name: string, func: unknown): void
  /**
   * Expose an async Node function to the VM. Unlike `exposeFunction`, the
   * function may return a Promise. VM code must `await` the call (use
   * `runAsync` to execute code that awaits). The VM thread parks until the
   * Promise settles on the Node event loop.
   */
  exposeAsyncFunction(name: string, func: unknown): void
  /**
   * Execute code that may `await` async host functions. Returns a Promise
   * that resolves with the stringified result once the VM finishes.
   *
   * Internally, the VM runs on a dedicated thread so that `await` can park
   * without blocking the Node event loop. Async host calls are dispatched
   * back to the main thread via a ThreadsafeFunction.
   *
   * **Throughput caveat:** each call spawns a new OS thread. Under
   * sustained high-frequency use (>100 calls/sec for extended periods),
   * the thread spawn/cleanup cycle can exhaust native resources and crash
   * the process. For high-frequency event handlers (chat messages, ticks),
   * prefer the synchronous `run()` which completes in microseconds for
   * typical workloads and never spawns a thread. Reserve `runAsync` for
   * genuinely heavy or long-running computation where blocking the event
   * loop is unacceptable.
   *
   * The caller must not call `run`/`runAsync` concurrently on the same VM.
   */
  runAsync(source: string): unknown
  /**
   * Remove a previously registered module so its exports are no longer
   * importable. Essential for hot-reload: call this before re-registering
   * a changed module to avoid stale export state.
   */
  removeModule(name: string): boolean
  /** Check whether a module with the given name is registered. */
  hasModule(name: string): boolean
  /** Return the names of all registered modules. */
  listModules(): Array<string>
  /**
   * Remove a global binding (including exposed host functions). Returns
   * `true` if the binding existed. Use before re-exposing a function on
   * hot-reload to avoid leaking stale references.
   */
  removeGlobal(name: string): boolean
  /** Check whether a global binding exists. */
  hasGlobal(name: string): boolean
  /**
   * Call a function defined in the VM (e.g. via a prior `run`) from Node,
   * marshalling arguments in and the return value out.
   */
  callFunction(name: string, args: Array<unknown>): unknown
  /**
   * Evaluate `source` and open the native interactive inspector on the
   * resulting value (a foldable, DevTools-style tree). The value is walked
   * directly inside Rust — no NAPI marshalling — so circular structures
   * render as `[Circular *n]`. In a non-TTY environment this prints a
   * static pretty dump instead and never blocks.
   *
   * Only available when the crate is built with `--features inspector`.
   */
  inspect(source: string): void
  /**
   * Marshal a host (Node) value into the VM and open the inspector on it —
   * convenient for inspecting a plain JS object without first registering
   * it as a global. To inspect parsed JSON, pass `JSON.parse(str)`.
   *
   * Unlike `inspect(source)`, the value is *copied* across the NAPI
   * boundary (`from_napi` is depth-bounded and not cycle-aware), so this
   * path cannot show circular structures. For those, build the value inside
   * the VM and inspect the expression instead.
   *
   * Only available when the crate is built with `--features inspector`.
   */
  inspectValue(value: unknown): void
}
export type VM = Vm

export declare function createVm(): Vm

export declare function debugParse(source: string): string

/**
 * Options for `setInspectorConfig`. Every field is optional; omitted fields
 * keep their current value. Letter-key overrides must be exactly one
 * character or they are ignored.
 */
export interface InspectorConfig {
  /** Force colors on/off; omit to keep auto-detection. */
  colors?: boolean
  /** Reserved for static-fallback tuning. */
  maxStaticDepth?: number
  keyUp?: string
  keyDown?: string
  keyExpand?: string
  keyCollapse?: string
  keyExpandAll?: string
  keyCollapseAll?: string
  keyQuit?: string
}

/** ANSI sequence to disable mouse tracking (reverse of `mouse_enable_seq`). */
export declare function mouseDisableSeq(): string

/**
 * ANSI sequence to enable button-event mouse tracking in SGR mode.
 *
 * `1000` = report button press events; `1006` = SGR extended encoding
 * (gives pixel-accurate coordinates and distinguishes press from release).
 */
export declare function mouseEnableSeq(): string

/** A parsed SGR mouse event, returned to JS as a plain object. */
export interface MouseEvent {
  /** `"press"`, `"release"`, `"move"`, `"scroll-up"`, or `"scroll-down"`. */
  kind: string
  /** 0-based column. */
  x: number
  /** 0-based row. */
  y: number
  /**
   * Button index: 0 = left, 1 = middle, 2 = right.
   * Always 0 for scroll events.
   */
  button: number
  shift: boolean
  alt: boolean
  ctrl: boolean
}

/**
 * Parse an SGR-encoded mouse event from raw stdin bytes.
 *
 * SGR format (mode 1006):
 *   press / move:  `\x1b[<Cb;Cx;CyM`
 *   release:       `\x1b[<Cb;Cx;Cym`
 *
 * Returns `None` when the buffer is not a valid SGR mouse sequence, so
 * callers can fall through to keyboard handling.
 */
export declare function parseMouseEvent(buf: Buffer): MouseEvent | null

export declare function runCode(source: string): string

/**
 * Override the global inspector configuration (keymap + colors). Changes
 * apply to the next `vm.inspect` / `console.dir({ inspect: true })` session.
 * Only available when built with `--features inspector`.
 */
export declare function setInspectorConfig(opts: InspectorConfig): void
