/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Vm {
  constructor()
  run(source: string): string
  registerModule(name: string, source: string): void
  setImportMetaMain(isMain: boolean): void
  getGlobal(name: string): string
}
export type VM = Vm

export declare function createVm(): Vm

export declare function debugParse(source: string): string

export declare function runCode(source: string): string
