/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Vm {
  constructor()
  run(source: string): string
  registerModule(name: string, source: string): void
  setImportMetaMain(isMain: boolean): void
  /**
   * Cap the number of loop iterations a single execution may perform
   * (default 100M). When the budget runs out, the VM throws a catchable
   * `RangeError` instead of freezing the host event loop forever.
   */
  setLoopLimit(n: number): void
  getGlobal(name: string): string
  /**
   * Define a global variable in the VM from a structured Node value. The
   * value is reachable both as a bare identifier and (once the global
   * aliases are wired) via `window`/`globalThis`/`self`.
   */
  setGlobal(name: string, value: unknown): void
  /**
   * Expose a Node function to the VM as a global. VM code can then call it
   * by name; arguments and the return value are marshalled across the
   * boundary, and a thrown error propagates into the VM as a catchable
   * exception.
   */
  exposeFunction(name: string, func: unknown): void
  /**
   * Expose an async Node function to the VM. Unlike `exposeFunction`, the
   * function may return a Promise. VM code must `await` the call (use
   * `runAsync` to execute code that awaits). The VM thread parks until the
   * Promise settles on the Node event loop.
   */
  exposeAsyncFunction(name: string, func: unknown): void
  /**
   * Execute code that may `await` async host functions. Returns a Promise
   * that resolves with the stringified result once the VM finishes.
   *
   * Internally, the VM runs on a dedicated thread so that `await` can park
   * without blocking the Node event loop. Async host calls are dispatched
   * back to the main thread via a ThreadsafeFunction.
   */
  runAsync(source: string): unknown
  /**
   * Remove a previously registered module so its exports are no longer
   * importable. Essential for hot-reload: call this before re-registering
   * a changed module to avoid stale export state.
   */
  removeModule(name: string): boolean
  /** Check whether a module with the given name is registered. */
  hasModule(name: string): boolean
  /** Return the names of all registered modules. */
  listModules(): Array<string>
  /**
   * Remove a global binding (including exposed host functions). Returns
   * `true` if the binding existed. Use before re-exposing a function on
   * hot-reload to avoid leaking stale references.
   */
  removeGlobal(name: string): boolean
  /** Check whether a global binding exists. */
  hasGlobal(name: string): boolean
  /**
   * Call a function defined in the VM (e.g. via a prior `run`) from Node,
   * marshalling arguments in and the return value out.
   */
  callFunction(name: string, args: Array<unknown>): unknown
}
export type VM = Vm

export declare function createVm(): Vm

export declare function debugParse(source: string): string

export declare function runCode(source: string): string
