import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdtemp,writeFile,rm,mkdir}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';import{createServer}from'node:http';
import{TrustedPluginHost,validateManifest,readManifest,resolveLaunch}from'../dist/index.js';
const root=fileURLToPath(new URL('../../../',import.meta.url));const contract=async name=>JSON.parse(await readFile(join(root,'contracts/trusted-plugins/generated/'+name+'.contract.json'),'utf8'));
const[G,C,COUNTER]=await Promise.all([contract('greeter'),contract('app-configuration'),contract('counter')]);
const bunPath=process.env.NAPI_VM_BUN??(process.versions.bun?process.execPath:undefined);
const runtimePaths={node:process.env.NAPI_VM_NODE??(process.versions.bun?'node':process.execPath),...(bunPath?{bun:bunPath}:{})};
function host(options={}){const h=new TrustedPluginHost({runtimePaths,...options});h.registerService(C,{get:()=>({value:'Hola'})});return h;}
test('real Node host/compiled TS plugin callback, errors, multiple instances, cleanup',{timeout:30000},async()=>{const h=host();try{const a=await h.load(join(root,'examples/trusted/greeter-ts'),{runtime:'node',development:true});const b=await h.load(join(root,'examples/trusted/greeter-ts'),{runtime:'node',development:true});assert.notEqual(a.instanceId,b.instanceId);assert.notEqual(a.sessionId,b.sessionId);assert.equal((await a.invoke(G,'greet',{name:'Ana'})).message,'Hola, Ana');await assert.rejects(a.invoke(G,'greet',{name:'invalid'}),e=>e.code==='APPLICATION_ERROR');assert.equal(h.list().length,2);await a.unload();await a.unload();assert.equal(a.status,'STOPPED');}finally{await h.shutdown();}});
test('real JS plugin uses same SDK without author TypeScript',{timeout:30000},async()=>{const h=host();try{const a=await h.load(join(root,'examples/trusted/greeter-js'),{runtime:'node',development:true});assert.equal((await a.invoke(G,'greet',{name:'JS'})).message,'Hola, JS');}finally{await h.shutdown();}});
test('stable generated client, validated event, stateful reload, repeated shutdown',{timeout:30000},async()=>{const h=host();try{const a=await h.load(join(root,'examples/trusted/counter-ts'),{runtime:'node',development:true});const client=a.client(COUNTER);let received;const event=new Promise(r=>received=r);const off=a.subscribe(COUNTER,'changed',received);assert.equal((await client.add({amount:12})).count,'12');assert.equal((await event).count,'12');const session=a.sessionId;await a.reload();assert.notEqual(session,a.sessionId);assert.equal((await client.get({})).count,'12');off();await a.unload();}finally{await h.shutdown();await h.shutdown();}});
test('callback cycle through independent host service fails promptly',{timeout:30000},async()=>{let a;const h=new TrustedPluginHost({runtimePaths});h.registerService(C,{get:async(_input,ctx)=>{await a.invoke(G,'greet',{name:'cycle'},{context:ctx});return{value:'bad'}}});try{a=await h.load(join(root,'examples/trusted/greeter-ts'),{runtime:'node',development:true});await assert.rejects(a.invoke(G,'greet',{name:'Ana'}),e=>e.code==='REENTRANT_CALL');}finally{await h.shutdown();}});
test('manifest rejects legacy, unknown fields, executable route and wrong runtime before spawn',{timeout:30000},async()=>{const m=JSON.parse(await readFile(join(root,'examples/trusted/greeter-ts/plugin.json'),'utf8'));assert.throws(()=>validateManifest({id:'legacy'}),/legacy/);assert.throws(()=>validateManifest({...m,permissions:{}}),/unknown field/);const r=await readManifest(join(root,'examples/trusted/greeter-ts'));await assert.rejects(resolveLaunch({...r,manifest:{...m,launch:{kind:'executable',entry:'dist/main.js',target:{os:'linux',arch:'x64'}}}},{runtime:'node'}),/TypeScript host supports/);await assert.rejects(resolveLaunch({...r,manifest:{...m,launch:{...m.launch,runtimes:['bun']}}},{runtime:'node'}),/not declared/);});
async function fixture(source,{requiresHost=false}={}){const dir=await mkdtemp(join(tmpdir(),'napi-vm test ü '));await mkdir(join(dir,'contracts'));await writeFile(join(dir,'contracts/greeter.json'),JSON.stringify(G));await writeFile(join(dir,'main.mjs'),`import{serve,definePlugin,PluginError}from ${JSON.stringify(pathToFileURL(join(root,'packages/plugin-sdk/dist/index.js')).href)};\nconst G=${JSON.stringify(G)};const C=${JSON.stringify(C)};\n${source}`);await writeFile(join(dir,'plugin.json'),JSON.stringify({manifestVersion:2,execution:'trusted-process',id:'example.greeter',version:'0.1.0',protocol:{major:1,minMinor:0,maxMinor:0},provides:{'example.greeter':'1.0.0'},requiresHost:requiresHost?{'app.configuration':'1.0.0'}:{},contracts:['contracts/greeter.json'],launch:{kind:'javascript',entry:'main.mjs',runtimes:['node','bun'],preferredRuntime:'node',args:[]},assets:[]}));return dir;}
test('failed initialization and shutdown hooks reap children and keep registry nonready',{timeout:30000},async()=>{for(const hooks of [`{initialize(){throw new Error('initialize broke')}}`,`{shutdown(){throw new Error('cleanup broke')}}`]){const dir=await fixture(`await serve(definePlugin(G,{greet:()=>({message:'ok'})},${hooks}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);const h=host();try{if(hooks.includes('initialize')){await assert.rejects(h.load(dir,{runtime:'node',development:true}));assert.equal(h.list()[0].status,'FAILED');assert.equal(h.list()[0].child,undefined);}else{const a=await h.load(dir,{runtime:'node',development:true});await a.unload();assert.equal(a.status,'STOPPED');assert.equal(a.child,undefined);}}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}}});
test('noisy stdout/stderr drains independently and retained memory is bounded',{timeout:30000},async()=>{const dir=await fixture(`process.stdout.write('x'.repeat(200000));process.stderr.write('y'.repeat(200000));await serve(definePlugin(G,{greet:()=>({message:'ok'})}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);const h=host({limits:{maxLogBytes:4096}});try{const a=await h.load(dir,{runtime:'node',development:true});assert.equal((await a.invoke(G,'greet',{name:'Ana'})).message,'ok');assert.ok(a.logBytes<=4096);assert.ok(a.droppedLogBytes>0);}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}});
test('trusted fixture direct filesystem outside plugin, HTTP, environment, controlled subprocess',{timeout:30000},async()=>{const dir=await fixture(`import{readFile,writeFile}from'node:fs/promises';import{spawnSync}from'node:child_process';await serve(definePlugin(G,{greet:async()=>{await writeFile(process.env.FIXTURE_FILE,'owned fixture');const text=await readFile(process.env.FIXTURE_FILE,'utf8');const response=await fetch(process.env.FIXTURE_HTTP);const child=spawnSync(process.execPath,['-e','process.stdout.write("child")'],{encoding:'utf8'});return{message:[text,await response.text(),process.env.FIXTURE_VALUE,child.stdout].join('|')}}}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);const outside=await mkdtemp(join(tmpdir(),'napi-vm-access-'));const http=createServer((_req,res)=>res.end('local-http'));await new Promise(r=>http.listen(0,'127.0.0.1',r));const h=host();try{const a=await h.load(dir,{runtime:'node',development:true,env:{FIXTURE_FILE:join(outside,'owned.txt'),FIXTURE_HTTP:`http://127.0.0.1:${http.address().port}`,FIXTURE_VALUE:'controlled'}});assert.equal((await a.invoke(G,'greet',{name:'Ana'})).message,'owned fixture|local-http|controlled|child');}finally{await h.shutdown();await new Promise(r=>http.close(r));await rm(dir,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});
test('host-to-plugin events validate negotiated service, are delivered outside reader, and acknowledge',{timeout:30000},async()=>{
 const dir=await fixture(`const K=${JSON.stringify(COUNTER)};let last='none';await serve(definePlugin(G,{greet:()=>({message:last})},{initialize(_,ctx){ctx.subscribe(K,'changed',async payload=>{last=payload.count;await ctx.invoke(K,'get',{});});}}),{metadata:{id:'example.greeter',version:'0.1.0',requiresHost:[K]}});`);
 const m=JSON.parse(await readFile(join(dir,'plugin.json'),'utf8'));m.requiresHost={'example.counter':'1.0.0'};m.contracts.push('contracts/counter.json');await writeFile(join(dir,'contracts/counter.json'),JSON.stringify(COUNTER));await writeFile(join(dir,'plugin.json'),JSON.stringify(m));
 let acknowledge;const delivered=new Promise(r=>acknowledge=r);const h=new TrustedPluginHost({runtimePaths});h.registerService(COUNTER,{get:()=>{acknowledge();return{count:'0'}},add:()=>({count:'0'})});
 try{const a=await h.load(dir,{runtime:'node',development:true});await assert.rejects(a.emit(COUNTER,'changed',{count:'invalid'}),e=>e.code==='INVALID_ARGUMENT');await a.emit(COUNTER,'changed',{count:'9'});await delivered;assert.equal((await a.invoke(G,'greet',{name:'Ana'})).message,'9');}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});
test('slow subscriber overflow terminates subscription with observable error without corrupting RPC',{timeout:30000},async()=>{
 const h=host({limits:{maxEventQueue:2}});let release;const blocked=new Promise(r=>release=r);let overflow;const overloaded=new Promise(r=>overflow=r);
 try{const a=await h.load(join(root,'examples/trusted/counter-ts'),{runtime:'node',development:true});a.subscribe(COUNTER,'changed',()=>blocked,e=>overflow(e));for(let i=0;i<5;i++)await a.invoke(COUNTER,'add',{amount:1});assert.equal((await overloaded).code,'OVERLOADED');assert.equal(a.status,'READY');assert.equal((await a.invoke(COUNTER,'get',{})).count,'5');}finally{release();await h.shutdown();}
});
test('failed quiescence preserves owned old process in DRAINING until explicit unload',{timeout:30000},async()=>{
 const dir=await fixture(`await serve(definePlugin(G,{greet:()=>({message:'ok'})},{quiesce(){throw new Error('drain fails')}}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);const h=host({limits:{shutdownTimeoutMs:200}});
 try{const a=await h.load(dir,{runtime:'node',development:true});const session=a.sessionId,pid=a.child.pid;await assert.rejects(a.reload(),e=>e.code==='INTERNAL_ERROR');assert.equal(a.status,'DRAINING');assert.equal(a.sessionId,session);assert.equal(a.child.pid,pid);await assert.rejects(a.invoke(G,'greet',{name:'Ana'}),e=>e.code==='NOT_READY');await a.unload();assert.equal(a.status,'STOPPED');}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});
test('failed replacement retains validated snapshot for explicit recovery, no hidden rollback',{timeout:30000},async()=>{
 const dir=await fixture(`const K=${JSON.stringify(COUNTER)};await serve(definePlugin(K,{get:()=>({count:'0'}),add:()=>({count:'0'})},{initialize(){throw new Error('restoration failed')},snapshot(){return{stateVersion:1,contract:'example.counter.state',data:{count:'0'}}}}),{metadata:{id:'example.counter',version:'0.1.0'}});`);
 const m=JSON.parse(await readFile(join(dir,'plugin.json'),'utf8'));m.id='example.counter';m.provides={'example.counter':'1.0.0'};m.contracts=['contracts/counter.json'];await writeFile(join(dir,'contracts/counter.json'),JSON.stringify(COUNTER));await writeFile(join(dir,'plugin.json'),JSON.stringify(m));const h=host();
 try{const a=await h.load(join(root,'examples/trusted/counter-ts'),{runtime:'node',development:true});await a.invoke(COUNTER,'add',{amount:19});await assert.rejects(a.reload(dir));assert.equal(a.status,'FAILED');assert.equal(a.child,undefined);assert.equal(a.snapshot.data.count,'19');await a.reload(join(root,'examples/trusted/counter-ts'));assert.equal((await a.invoke(COUNTER,'get',{})).count,'19');}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});
test('bootstrap token is redacted across stdout/stderr chunk boundaries',{timeout:30000},async()=>{
 const dir=await fixture(`const token=process.env.NAPI_VM_PLUGIN_TOKEN;process.stdout.write('before:'+token.slice(0,17));await new Promise(r=>setTimeout(r,10));process.stdout.write(token.slice(17)+':after');process.stderr.write(token);await serve(definePlugin(G,{greet:()=>({message:'ok'})}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);const h=host();const emitted=[];h.on('log',event=>emitted.push(event.text));try{const a=await h.load(dir,{runtime:'node',development:true});await a.unload();const text=a.logs.map(x=>x.text).join('');assert.match(a.logs.filter(x=>x.stream==='stdout').map(x=>x.text).join(''),/before:\[REDACTED\]:after/);assert.ok(!/[a-f0-9]{64}/.test(text));assert.ok(!/[a-f0-9]{64}/.test(emitted.join('')));}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});
test('wrong-token connection cannot steal the legitimate child slot',{timeout:30000},async()=>{
 const protocol=pathToFileURL(join(root,'packages/plugin-protocol/dist/index.js')).href;
 const dir=await fixture(`import{connect}from'node:net';import{RpcPeer}from ${JSON.stringify(protocol)};const port=Number(process.env.NAPI_VM_PLUGIN_ENDPOINT.split(':')[1]);const socket=connect(port,'127.0.0.1');await new Promise(r=>socket.once('connect',r));const bad=new RpcPeer(socket,{role:'p',sessionId:process.env.NAPI_VM_PLUGIN_SESSION_ID});try{await bad.request('system.hello',{token:'0'.repeat(64),instanceId:process.env.NAPI_VM_PLUGIN_INSTANCE_ID,sessionId:process.env.NAPI_VM_PLUGIN_SESSION_ID,pluginId:'example.greeter',pluginVersion:'0.1.0',protocol:{major:1,minMinor:0,maxMinor:0},interfaces:{},requiresHost:{},extensions:[]});}catch{}finally{bad.close();}await serve(definePlugin(G,{greet:()=>({message:'valid child'})}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);
 const h=host();try{const a=await h.load(dir,{runtime:'node',development:true});assert.equal((await a.invoke(G,'greet',{name:'Ana'})).message,'valid child');}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});
test('authorized protocol and digest mismatch reject before initialize',{timeout:30000},async()=>{
 const protocol=pathToFileURL(join(root,'packages/plugin-protocol/dist/index.js')).href;
 for(const mismatch of ['protocol','digest']){const dir=await fixture(`import{connect}from'node:net';import{RpcPeer}from ${JSON.stringify(protocol)};const socket=connect(Number(process.env.NAPI_VM_PLUGIN_ENDPOINT.split(':')[1]),'127.0.0.1');await new Promise(r=>socket.once('connect',r));const peer=new RpcPeer(socket,{role:'p',sessionId:process.env.NAPI_VM_PLUGIN_SESSION_ID});await peer.request('system.hello',{token:process.env.NAPI_VM_PLUGIN_TOKEN,instanceId:process.env.NAPI_VM_PLUGIN_INSTANCE_ID,sessionId:process.env.NAPI_VM_PLUGIN_SESSION_ID,pluginId:'example.greeter',pluginVersion:'0.1.0',protocol:{major:${mismatch==='protocol'?2:1},minMinor:0,maxMinor:0},interfaces:{'example.greeter':{version:'1.0.0',digest:${mismatch==='digest'?JSON.stringify('0'.repeat(64)):'G.digest'}}},requiresHost:{},extensions:[]});`);const h=host();try{await assert.rejects(h.load(dir,{runtime:'node',development:true}),e=>e.code===(mismatch==='protocol'?'PROTOCOL_MISMATCH':'CONTRACT_MISMATCH'));assert.equal(h.list()[0].status,'FAILED');assert.equal(h.list()[0].child,undefined);}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}}
});
test('startup deadline, exit before hello, and exit during invocation are bounded and reaped',{timeout:30000},async()=>{
 for(const behavior of ['hang','exit','invoke']){const source=behavior==='hang'?`setInterval(()=>{},1000);`:behavior==='exit'?`process.exit(42);`:`await serve(definePlugin(G,{greet:()=>{process.exit(42)}}),{metadata:{id:'example.greeter',version:'0.1.0'}});`;const dir=await fixture(source);const h=host({limits:{startupTimeoutMs:behavior==='hang'?100:5000,shutdownTimeoutMs:200}});try{if(behavior==='invoke'){const a=await h.load(dir,{runtime:'node',development:true});await assert.rejects(a.invoke(G,'greet',{name:'Ana'}),e=>['PLUGIN_EXITED','CONNECTION_CLOSED'].includes(e.code));}else await assert.rejects(h.load(dir,{runtime:'node',development:true}),e=>e.code===(behavior==='hang'?'DEADLINE_EXCEEDED':'PLUGIN_EXITED'));}finally{await h.shutdown();assert.ok(h.list().every(a=>a.child===undefined));await rm(dir,{recursive:true,force:true});}}
});
test('missing runtime is preflight failure and plugin startup failure never retries another runtime',{timeout:30000},async()=>{
 const dir=await fixture(`import{appendFileSync}from'node:fs';appendFileSync(process.env.FIXTURE_ATTEMPTS,'attempt\\n');process.exit(42);`);const attempts=join(dir,'attempts');const h=new TrustedPluginHost({runtimePaths:{node:join(dir,'missing-node'),bun:join(dir,'missing-bun')}});try{await assert.rejects(h.load(dir,{runtime:'node',development:true}),/No compatible declared runtime/);assert.equal(h.list().length,0);}finally{await h.shutdown();}
 const real=host();try{await assert.rejects(real.load(dir,{development:true,env:{FIXTURE_ATTEMPTS:attempts}}),e=>e.code==='PLUGIN_EXITED');assert.equal(await readFile(attempts,'utf8'),'attempt\n');}finally{await real.shutdown();await rm(dir,{recursive:true,force:true});}
});
test('managed Bun missing package fails without runtime registry installation',{timeout:30000,skip:!bunPath},async()=>{
 const dir=await fixture(`import 'napi-vm-controlled-missing-dependency-never-published-98a217';await serve(definePlugin(G,{greet:()=>({message:'impossible'})}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);const h=host();try{const resolved=await readManifest(dir);const launch=await resolveLaunch(resolved,{runtime:'bun',runtimePaths,development:true});assert.ok(launch.args.includes('--no-install'));await assert.rejects(h.load(dir,{runtime:'bun',development:true}),e=>e.code==='PLUGIN_EXITED');await assert.rejects(readFile(join(dir,'bun.lock')));await assert.rejects(readFile(join(dir,'package-lock.json')));}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});
test('control parameter validation rejects malformed lifecycle requests without changing READY',{timeout:30000},async()=>{
 const h=host();try{const a=await h.load(join(root,'examples/trusted/greeter-ts'),{runtime:'node',development:true});for(const[method,params]of[['system.quiesce',{timeoutMs:0}],['system.quiesce',{timeoutMs:1.5}],['system.quiesce',{unknown:true}],['system.snapshot',{unknown:true}],['system.shutdown',{unknown:true}],['system.ping',null],['system.ping',{unknown:true}]])await assert.rejects(a.peer.request(method,params),e=>e.code==='INVALID_ARGUMENT');assert.equal(a.status,'READY');assert.equal(await a.peer.request('system.ping',{}),null);assert.equal((await a.invoke(G,'greet',{name:'Ana'})).message,'Hola, Ana');}finally{await h.shutdown();}
});
test('queued old-session events are discarded across reload while in-progress callback can finish',{timeout:30000},async()=>{
 const h=host();let release,entered,seenNew;const gate=new Promise(r=>release=r),first=new Promise(r=>entered=r),newEvent=new Promise(r=>seenNew=r);const seen=[];
 try{const a=await h.load(join(root,'examples/trusted/counter-ts'),{runtime:'node',development:true});a.subscribe(COUNTER,'changed',async payload=>{seen.push(payload.count);if(seen.length===1){entered();await gate;}else seenNew();});await a.invoke(COUNTER,'add',{amount:1});await first;await a.invoke(COUNTER,'add',{amount:1});await a.reload();release();await a.invoke(COUNTER,'add',{amount:1});await newEvent;assert.deepEqual(seen,['1','3']);assert.ok(a.discardedStaleEvents>=1);}finally{release?.();await h.shutdown();}
});
test('direct child exit does not hang on a descendant retaining inherited log pipes',{timeout:30000},async()=>{
 const dir=await fixture(`import{spawn}from'node:child_process';import{writeFileSync}from'node:fs';const child=spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:['ignore','inherit','inherit']});writeFileSync(process.env.FIXTURE_PID,String(child.pid));process.exit(42);`);const pidFile=join(dir,'descendant.pid');const h=host();let timer;
 try{await assert.rejects(Promise.race([h.load(dir,{runtime:'node',development:true,env:{FIXTURE_PID:pidFile}}),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Host waited for escaped descendant pipes')),10000)})]),e=>e.code==='PLUGIN_EXITED');assert.equal(h.list()[0].child,undefined);}finally{clearTimeout(timer);try{const pid=Number(await readFile(pidFile,'utf8'));process.kill(pid,'SIGKILL');}catch{}await h.shutdown();await rm(dir,{recursive:true,force:true});}
});

test('quiescence lets an in-flight handler finish its event and result before snapshot',{timeout:30000},async()=>{
 const dir=await fixture(`const K=${JSON.stringify(COUNTER)};let count=0n;await serve(definePlugin(K,{add:async({amount},ctx)=>{await ctx.invoke(C,'get',{key:'barrier'});count+=BigInt(amount);await ctx.emit(K,'changed',{count:count.toString()});return{count:count.toString()};},get:()=>({count:count.toString()})},{initialize({snapshot}){if(snapshot)count=BigInt(snapshot.data.count);},snapshot(){return{stateVersion:1,contract:'example.counter.state',data:{count:count.toString()}};}}),{metadata:{id:'example.counter',version:'0.1.0',requiresHost:[C]}});`,{requiresHost:true});
 const m=JSON.parse(await readFile(join(dir,'plugin.json'),'utf8'));m.id='example.counter';m.provides={'example.counter':'1.0.0'};m.contracts=['contracts/counter.json','contracts/configuration.json'];await writeFile(join(dir,'contracts/counter.json'),JSON.stringify(COUNTER));await writeFile(join(dir,'contracts/configuration.json'),JSON.stringify(C));await writeFile(join(dir,'plugin.json'),JSON.stringify(m));
 let entered,release;const started=new Promise(r=>entered=r),barrier=new Promise(r=>release=r);const h=new TrustedPluginHost({runtimePaths});h.registerService(C,{get:async()=>{entered();await barrier;return{value:'ok'};}});
 try{const p=await h.load(dir,{runtime:'node',development:true});const result=p.invoke(COUNTER,'add',{amount:1}).then(value=>({value}),error=>({error}));await started;const draining=new Promise(r=>h.on('status',s=>{if(s.instanceId===p.instanceId&&s.status==='DRAINING')r();}));const reload=p.reload();await draining;release();const outcome=await result;await reload;assert.equal(outcome.error,undefined);assert.equal(outcome.value.count,'1');assert.equal((await p.invoke(COUNTER,'get',{})).count,'1');}finally{release();await h.shutdown();await rm(dir,{recursive:true,force:true});}
});

test('a call-bound host callback context cannot invoke a replacement session',{timeout:30000},async()=>{
 let captured;const h=new TrustedPluginHost({runtimePaths});h.registerService(C,{get:(_input,ctx)=>{captured=ctx;return{value:'Hola'};}});
 try{const p=await h.load(join(root,'examples/trusted/greeter-ts'),{runtime:'node',development:true});await p.invoke(G,'greet',{name:'Ana'});const retired=captured;await p.reload();await assert.rejects(retired.invoke(G,'greet',{name:'Retired'}),e=>e.code==='CONNECTION_CLOSED');assert.equal((await p.invoke(G,'greet',{name:'Current'})).message,'Hola, Current');}finally{await h.shutdown();}
});

test('process initialization preserves explicit null configuration and rejects nonobject application context',{timeout:30000},async()=>{
 const dir=await fixture(`let received;await serve(definePlugin(G,{greet:()=>({message:JSON.stringify(received)})},{initialize(input){received=input.configuration;}}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);const h=host();
 try{for(const [options,expected]of [[{},'{}'],[{configuration:null},'null']]){const p=await h.load(dir,{runtime:'node',development:true,...options});assert.equal((await p.invoke(G,'greet',{name:'Ana'})).message,expected);await p.unload();}const before=h.list().length;await assert.rejects(h.load(dir,{runtime:'node',development:true,context:null}),e=>e.code==='INVALID_ARGUMENT');assert.equal(h.list().length,before);let accessed=false;const context={get value(){accessed=true;return 'bad';}};await assert.rejects(h.load(dir,{runtime:'node',development:true,context}),e=>e.code==='INVALID_ARGUMENT');assert.equal(accessed,false);assert.equal(h.list().length,before);}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});

test('injected service credentials are redacted in decoded and URL-encoded logs',{timeout:30000},async()=>{
 const service={url:'https://user:p%40ssword@example.invalid/api?token=query%20secret',headers:{Authorization:'Bearer header-secret'}};
 const dir=await fixture(`await serve(definePlugin(G,{greet:()=>({message:'ok'})},{initialize(input){const service=input.context.services.remote;process.stdout.write(service.url+'|p%40ssword|p@ssword|query%20secret|query secret|'+service.headers.Authorization);}}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);
 const manifest=JSON.parse(await readFile(join(dir,'plugin.json'),'utf8'));manifest.dependencies={native:[],services:[{name:'remote',kind:'http',owner:'external'}],capabilities:[]};await writeFile(join(dir,'plugin.json'),JSON.stringify(manifest));
 const h=host();const emitted=[];h.on('log',entry=>emitted.push(entry.text));
 try{const p=await h.load(dir,{runtime:'node',development:true,services:{remote:service}});await p.unload();for(const text of [p.logs.map(entry=>entry.text).join(''),emitted.join('')]){assert.match(text,/\[REDACTED\]/);for(const secret of [service.url,'p%40ssword','p@ssword','query%20secret','query secret',service.headers.Authorization])assert.equal(text.includes(secret),false);}}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});

test('caller environment values and bootstrap tokens are redacted across both log streams',{timeout:30000},async()=>{
 const secret='caller-env-secret-ü-123456789';
 const dir=await fixture(`const secret=process.env.CALLER_SECRET;const token=process.env.NAPI_VM_PLUGIN_TOKEN;for(const stream of [process.stdout,process.stderr]){stream.write('before:'+secret.slice(0,9));await new Promise(r=>setTimeout(r,10));stream.write(secret.slice(9)+'|'+token.slice(0,17));await new Promise(r=>setTimeout(r,10));stream.write(token.slice(17)+':after');}await serve(definePlugin(G,{greet:()=>({message:'ok'})}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);
 const h=host();const emitted={stdout:[],stderr:[]};h.on('log',entry=>emitted[entry.stream].push(entry.text));
 try{const p=await h.load(dir,{runtime:'node',development:true,env:{CALLER_SECRET:secret,EMPTY_VALUE:''}});await p.unload();for(const stream of ['stdout','stderr']){for(const text of [p.logs.filter(entry=>entry.stream===stream).map(entry=>entry.text).join(''),emitted[stream].join('')]){assert.equal(text,'before:[REDACTED]|[REDACTED]:after');assert.equal(text.includes(secret),false);assert.equal(/[a-f0-9]{64}/.test(text),false);}}}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});

test('plugin initialization and invocation errors redact registered credentials while preserving codes',{timeout:30000},async()=>{
 const secret='caller-error-secret-123456789';const service={url:'https://example.invalid/?token=service-query-secret',headers:{Authorization:'Bearer service-header-secret'}};
 for(const initializeFailure of [true,false]){
  const source=`let credentials;const fail=()=>{const error=new PluginError('INTERNAL_ERROR','safe-prefix:'+credentials,{nested:[{credentials}]});throw error;};await serve(definePlugin(G,{greet:input=>{if(input.name==='Domain')throw PluginError.domain('INVALID_NAME',{reason:credentials},'domain-prefix:'+credentials);return fail();}},{initialize(input){credentials=[process.env.CALLER_SECRET,process.env.NAPI_VM_PLUGIN_TOKEN,input.context.services.remote.url,input.context.services.remote.headers.Authorization].join('|');${initializeFailure?'fail();':''}}}),{metadata:{id:'example.greeter',version:'0.1.0'}});`;
  const dir=await fixture(source);const manifest=JSON.parse(await readFile(join(dir,'plugin.json'),'utf8'));manifest.dependencies={native:[],services:[{name:'remote',kind:'http',owner:'external'}],capabilities:[]};await writeFile(join(dir,'plugin.json'),JSON.stringify(manifest));const h=host();
  const safe=error=>{assert.equal(error.code,'INTERNAL_ERROR');assert.equal(error.message,'safe-prefix:[REDACTED]|[REDACTED]|[REDACTED]|[REDACTED]');assert.equal(error.details.nested[0].credentials,'[REDACTED]|[REDACTED]|[REDACTED]|[REDACTED]');assert.equal(JSON.stringify(error).includes(secret),false);assert.equal(/[a-f0-9]{64}/.test(JSON.stringify(error)),false);return true;};
  try{const options={runtime:'node',development:true,env:{CALLER_SECRET:secret},services:{remote:service}};if(initializeFailure){await assert.rejects(h.load(dir,options),safe);assert.equal(h.list()[0].status,'FAILED');assert.equal(h.list()[0].child,undefined);}else{const p=await h.load(dir,options);await assert.rejects(p.invoke(G,'greet',{name:'Ana'}),safe);await assert.rejects(p.invoke(G,'greet',{name:'Domain'}),error=>{assert.equal(error.code,'APPLICATION_ERROR');assert.equal(error.domainCode,'INVALID_NAME');assert.equal(error.message,'domain-prefix:[REDACTED]|[REDACTED]|[REDACTED]|[REDACTED]');assert.equal(error.data.reason,'[REDACTED]|[REDACTED]|[REDACTED]|[REDACTED]');return true;});assert.equal(p.status,'READY');}}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
 }
});

test('redaction preserves canonical error identifiers when caller environment values match them',{timeout:30000},async()=>{
 const dir=await fixture(`await serve(definePlugin(G,{greet:()=>{throw PluginError.domain('INVALID_NAME',{reason:'ordinary reason'});}}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);const h=host();
 try{const p=await h.load(dir,{runtime:'node',development:true,env:{MATCHED_CODE:'APPLICATION_ERROR',MATCHED_DOMAIN:'INVALID_NAME'}});await assert.rejects(p.invoke(G,'greet',{name:'Ana'}),error=>{assert.equal(error.code,'APPLICATION_ERROR');assert.equal(error.domainCode,'INVALID_NAME');assert.equal(error.message,'[REDACTED]');assert.equal(error.data.reason,'ordinary reason');return true;});assert.equal('errorSanitizer' in h,false);}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});

test('authorization credential suffixes and URL usernames redact in logs and nested plugin errors',{timeout:30000},async()=>{
 const service={url:'https://url%2Dauth%2Dsecret@example.invalid',headers:{aUtHoRiZaTiOn:'Bearer bare-auth-secret','Proxy-Authorization':'Basic bare-proxy-secret'}};
 const dir=await fixture(`let bare;await serve(definePlugin(G,{greet:()=>{throw new PluginError('INTERNAL_ERROR','credentials:'+bare,{nested:{bare}});}},{initialize(input){const headers=input.context.services.remote.headers;const url=new URL(input.context.services.remote.url);bare=[url.username,decodeURIComponent(url.username),...Object.values(headers).map(value=>value.split(' ')[1])].join('|');process.stdout.write(bare);process.stderr.write(bare);}}),{metadata:{id:'example.greeter',version:'0.1.0'}});`);
 const manifest=JSON.parse(await readFile(join(dir,'plugin.json'),'utf8'));manifest.dependencies={native:[],services:[{name:'remote',kind:'http',owner:'external'}],capabilities:[]};await writeFile(join(dir,'plugin.json'),JSON.stringify(manifest));const h=host();const emitted={stdout:[],stderr:[]};h.on('log',entry=>emitted[entry.stream].push(entry.text));
 try{const p=await h.load(dir,{runtime:'node',development:true,services:{remote:service}});await assert.rejects(p.invoke(G,'greet',{name:'Ana'}),error=>{assert.equal(error.code,'INTERNAL_ERROR');assert.equal(error.message,'credentials:[REDACTED]|[REDACTED]|[REDACTED]|[REDACTED]');assert.equal(error.details.nested.bare,'[REDACTED]|[REDACTED]|[REDACTED]|[REDACTED]');return true;});await p.unload();for(const stream of ['stdout','stderr']){assert.equal(p.logs.filter(entry=>entry.stream===stream).map(entry=>entry.text).join(''),'[REDACTED]|[REDACTED]|[REDACTED]|[REDACTED]');assert.equal(emitted[stream].join(''),'[REDACTED]|[REDACTED]|[REDACTED]|[REDACTED]');}}finally{await h.shutdown();await rm(dir,{recursive:true,force:true});}
});
