import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,cp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {TrustedPluginHost} from '@napi-vm/plugin-host';
import {pack} from '../../../packages/plugin-cli/src/pack.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url));
test('relocated package retains declared assets and dynamic imports',{timeout:30000},async()=>{const dir=await mkdtemp(join(tmpdir(),'plugin assets café '));try{const source=join(dir,'source');await mkdir(join(source,'assets'),{recursive:true});const contract=JSON.parse(await readFile(join(root,'contracts/trusted-plugins/generated/greeter.contract.json'),'utf8'));await writeFile(join(source,'contract.json'),JSON.stringify(contract));await writeFile(join(source,'assets/message.txt'),'portable asset');await writeFile(join(source,'assets/late.mjs'),'export const prefix="Hello";\n');await writeFile(join(source,'main.mjs'),`import {readFile} from 'node:fs/promises';import {definePlugin,serve} from '@napi-vm/plugin-sdk';const c=JSON.parse(await readFile(new URL('./contract.json',import.meta.url),'utf8'));await serve(definePlugin(c,{greet:async({name})=>{const {prefix}=await import('./assets/late.mjs');const text=await readFile(new URL('./assets/message.txt',import.meta.url),'utf8');return{message:prefix+' '+name+': '+text};}}),{metadata:{id:'example.assets',version:'0.1.0'}});`);for(const name of ['plugin-protocol','plugin-sdk']){const dest=join(source,'node_modules/@napi-vm',name);await mkdir(dest,{recursive:true});await cp(join(root,'packages',name,'dist'),join(dest,'dist'),{recursive:true});await cp(join(root,'packages',name,'package.json'),join(dest,'package.json'));await cp(join(root,'packages',name,'LICENSE'),join(dest,'LICENSE'));}
await writeFile(join(source,'plugin.json'),JSON.stringify({manifestVersion:2,execution:'trusted-process',id:'example.assets',version:'0.1.0',protocol:{major:1,minMinor:0,maxMinor:0},profile:'portable-js',provides:{'example.greeter':'1.0.0'},requiresHost:{},launch:{kind:'javascript',entry:'main.mjs',runtimes:['node','bun'],preferredRuntime:'node',args:[]},contracts:['contract.json'],assets:['assets/message.txt','assets/late.mjs'],extensions:{'napi-vm.pack':{include:['node_modules/@napi-vm/plugin-protocol','node_modules/@napi-vm/plugin-sdk']}}}));const output=join(dir,'moved elsewhere');await pack(source,output);await rm(source,{recursive:true,force:true});for(const runtime of ['node','bun']){const host=new TrustedPluginHost();try{const p=await host.load(join(output,'plugin.json'),{runtime});assert.equal((await p.invoke(contract,'greet',{name:'Ana'})).message,'Hello Ana: portable asset');}finally{await host.shutdown();}}}finally{await rm(dir,{recursive:true,force:true});}});
