import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,cp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {TrustedPluginHost} from '@napi-vm/plugin-host';
import {pack} from '../../../packages/plugin-cli/src/pack.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url));
test('controlled Node-API dependency is target inventoried and injected',{skip:process.platform!=='linux',timeout:30000},async()=>{const dir=await mkdtemp(join(tmpdir(),'native dependency '));const stage=join(dir,'source');await mkdir(stage);const target=join(stage,'answer.node');try{const compiler=spawnSync('cc',['-shared','-fPIC',join(root,'tests/fixtures/node-api/node-api-smoke.c'),'-o',target],{encoding:'utf8'});assert.equal(compiler.status,0,compiler.stderr||compiler.error?.message);const probe=spawnSync(process.execPath,['-e','process.stdout.write(String(require(process.argv[1]).answer))',target],{encoding:'utf8'});assert.equal(probe.status,0,probe.stderr);assert.equal(probe.stdout,'42');
const contract=JSON.parse(await readFile(join(root,'contracts/trusted-plugins/generated/greeter.contract.json'),'utf8'));await writeFile(join(stage,'contract.json'),JSON.stringify(contract));await writeFile(join(stage,'main.mjs'),`import {readFile} from 'node:fs/promises';import {createRequire} from 'node:module';import {definePlugin,serve} from '@napi-vm/plugin-sdk';const c=JSON.parse(await readFile(new URL('./contract.json',import.meta.url),'utf8'));let answer;await serve(definePlugin(c,{greet:async()=>({message:String(answer)})},{initialize:async ({context})=>{answer=createRequire(import.meta.url)(context.nativeDependencies.answer.path).answer;}}),{metadata:{id:'example.native-probe',version:'0.1.0'}});`);
for(const name of ['plugin-protocol','plugin-sdk']){const dest=join(stage,'node_modules/@napi-vm',name);await mkdir(dest,{recursive:true});await cp(join(root,'packages',name,'dist'),join(dest,'dist'),{recursive:true});await cp(join(root,'packages',name,'package.json'),join(dest,'package.json'));}
const manifest={manifestVersion:2,execution:'trusted-process',id:'example.native-probe',version:'0.1.0',protocol:{major:1,minMinor:0,maxMinor:0},profile:'external-runtime',provides:{'example.greeter':'1.0.0'},requiresHost:{},launch:{kind:'javascript',entry:'main.mjs',runtimes:['node'],preferredRuntime:'node',args:[]},contracts:['contract.json'],assets:[],dependencies:{native:[{name:'answer',path:'answer.node',target:{os:'linux',arch:process.arch,libc:process.report.getReport().header.glibcVersionRuntime?'gnu':'musl'},abi:'napi-1',runtime:'node',status:'tested'}],services:[],capabilities:[]},extensions:{'napi-vm.pack':{include:['node_modules/@napi-vm/plugin-protocol','node_modules/@napi-vm/plugin-sdk']}}};await writeFile(join(stage,'plugin.json'),JSON.stringify(manifest));const output=join(dir,'packed');await pack(stage,output);const host=new TrustedPluginHost();try{const handle=await host.load(join(output,'plugin.json'),{runtime:'node'});const result=await handle.invoke(contract,'greet',{name:'Ada'});assert.equal(result.message,'42');}finally{await host.shutdown();}
}finally{await rm(dir,{recursive:true,force:true});}});
