import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir,rm,symlink,stat,access,cp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {main} from '../src/index.mjs';
import {pack,contained,prepareDevelopmentPackage,currentTarget} from '../src/pack.mjs';
const contract=JSON.parse(await readFile(new URL('../../../contracts/trusted-plugins/generated/greeter.contract.json',import.meta.url),'utf8'));
async function fixture(root){const dir=join(root,'source with spaces 🌍');await mkdir(join(dir,'dist'),{recursive:true});await mkdir(join(dir,'contracts'));await writeFile(join(dir,'dist/main.js'),'console.log("owned test fixture");\n');await writeFile(join(dir,'contracts/greeter.contract.json'),JSON.stringify(contract));await writeFile(join(dir,'plugin.json'),JSON.stringify({manifestVersion:2,execution:'trusted-process',id:'example.greeter',version:'0.1.0',protocol:{major:1,minMinor:0,maxMinor:0},provides:{'example.greeter':'1.0.0'},requiresHost:{},launch:{kind:'javascript',entry:'./dist/main.js',runtimes:['node'],preferredRuntime:'node',args:[]},assets:[],contracts:['./contracts/greeter.contract.json']}));return dir;}
test('create provides real templates and never overwrites',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-create-'));try{for(const language of ['ts','js','rust']){const destination=join(root,language);await main(['create',destination,'--language',language]);assert.equal((await stat(join(destination,'src',language==='rust'?'lib.rs':'plugin.'+language))).isFile(),true);if(language!=='rust'){const pkg=JSON.parse(await readFile(join(destination,'package.json'),'utf8'));assert.equal(pkg.dependencies['@napi-vm/plugin-sdk'],'file:vendor/plugin-sdk');assert.equal(pkg.devDependencies['@napi-vm/plugin-cli'],'file:vendor/plugin-cli');for(const name of ['plugin-protocol','plugin-sdk','plugin-host','plugin-codegen','plugin-cli']){const vendored=JSON.parse(await readFile(join(destination,'vendor',name,'package.json'),'utf8'));for(const [dependency,version]of Object.entries(vendored.dependencies??{}))if(dependency.startsWith('@napi-vm/'))assert.match(version,/^file:\.\.\//);await assert.rejects(stat(join(destination,'vendor',name,'node_modules')),/ENOENT/);}}await assert.rejects(main(['create',destination,'--language',language]),/overwrite/);}await assert.rejects(main(['create',join(root,'bad'),'--language','python']),/language/);}finally{await rm(root,{recursive:true,force:true});}});
test('pack creates relocatable complete inventory and detects tampering',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-pack-'));try{const dir=await fixture(root);const out=join(root,'package with spaces 🌍');const result=await pack(dir,out);assert.deepEqual(result.lock.artifact.availability,{built:true,distributed:false,tested:[]});assert.equal(result.lock.files['plugin.json'].length,64);await main(['validate',out]);await assert.rejects(pack(dir,out),/already exists/);await writeFile(join(out,'dist/main.js'),'tampered');await assert.rejects(main(['validate',out]),/integrity|checksum|mismatch/i);}finally{await rm(root,{recursive:true,force:true});}});
test('unsafe paths, outside symlinks, directory cycles and secrets fail before output',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-paths-'));try{const dir=await fixture(root);for(const path of ['../outside','dist/../main.js','C:\\outside','/etc/passwd','dist//main.js'])await assert.rejects(contained(dir,path),/Unsafe/);await writeFile(join(root,'outside'),'test');await symlink(join(root,'outside'),join(dir,'escape'));await assert.rejects(contained(dir,'escape'),/escapes/);const m=JSON.parse(await readFile(join(dir,'plugin.json'),'utf8'));m.assets=['.env'];await writeFile(join(dir,'.env'),'FIXTURE=not-a-secret');await writeFile(join(dir,'plugin.json'),JSON.stringify(m));await assert.rejects(pack(dir,join(root,'secrets')),/sensitive/);m.assets=['cycle'];await symlink(dir,join(dir,'cycle'));await writeFile(join(dir,'plugin.json'),JSON.stringify(m));await assert.rejects(pack(dir,join(root,'cycles')),/escapes|cycle|unsafe/i);}finally{await rm(root,{recursive:true,force:true});}});
test('CLI rejects missing option values and invalid JSON without loading',async()=>{await assert.rejects(main(['pack','.','--out']),/requires a value/);await assert.rejects(main(['invoke','.','--interface','example.greeter','--method','greet','--input','{']),SyntaxError);await assert.rejects(main(['no-such-command']),/Unknown command/);});
test('doctor validates runtime names before probing executables',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-doctor-'));try{const dir=await fixture(root);const path=join(dir,'plugin.json');const manifest=JSON.parse(await readFile(path,'utf8'));manifest.launch.runtimes=['/untrusted/not-a-runtime'];manifest.launch.preferredRuntime='/untrusted/not-a-runtime';await writeFile(path,JSON.stringify(manifest));const result=await main(['doctor',dir]);assert.equal(result.validation.valid,false);assert.deepEqual(result.runtimes,[]);}finally{await rm(root,{recursive:true,force:true});}});
test('CLI entrypoint runs through an npm-style bin symlink',async()=>{const {spawnSync}=await import('node:child_process');const {fileURLToPath}=await import('node:url');const root=await mkdtemp(join(tmpdir(),'plugin-bin-'));try{const bin=join(root,'napi-vm-plugin.mjs');await symlink(fileURLToPath(new URL('../src/index.mjs',import.meta.url)),bin,'file');const result=spawnSync(process.execPath,[bin,'help'],{encoding:'utf8',timeout:10000});assert.equal(result.status,0,result.stderr);assert.match(JSON.parse(result.stdout).help,/create <directory>/);}finally{await rm(root,{recursive:true,force:true});}});

test('native dev launch stages have verified inventories before host startup',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-native-dev-'));try{const directory=await fixture(root);const manifestPath=join(directory,'plugin.json');const manifest=JSON.parse(await readFile(manifestPath,'utf8'));const entry='dist/plugin'+(process.platform==='win32'?'.exe':'');await writeFile(join(directory,entry),'Controlled packaging fixture; not launched by this unit test.\n',{mode:0o755});manifest.profile='native-executable';manifest.launch={kind:'executable',entry,args:[],target:currentTarget()};await writeFile(manifestPath,JSON.stringify(manifest));const launchDirectory=await prepareDevelopmentPackage(directory,'executable');assert.notEqual(launchDirectory,directory);const lock=JSON.parse(await readFile(join(launchDirectory,'plugin.lock.json'),'utf8'));assert.equal(lock.artifact.profile,'native-executable');assert.equal(lock.files[entry].length,64);await main(['validate',launchDirectory]);assert.equal(await prepareDevelopmentPackage(directory,'js'),directory);await assert.rejects(prepareDevelopmentPackage(directory,'executable'),/already exists/);}finally{await rm(root,{recursive:true,force:true});}});

test('pack rejects aliases of secret files and broken links without partial output',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-secret-alias-'));try{const directory=await fixture(root);const manifestPath=join(directory,'plugin.json');const manifest=JSON.parse(await readFile(manifestPath,'utf8'));manifest.assets=['innocent.txt'];await writeFile(manifestPath,JSON.stringify(manifest));const out=join(root,'output');for(const secret of ['.env','.ENV']){await writeFile(join(directory,secret),'TOKEN=fixture');await symlink(secret,join(directory,'innocent.txt'),'file');await assert.rejects(pack(directory,out),/sensitive/);await assert.rejects(access(out),/ENOENT/);await rm(join(directory,'innocent.txt'));}await symlink('does-not-exist',join(directory,'innocent.txt'),'file');await assert.rejects(pack(directory,out),/ENOENT/);await assert.rejects(access(out),/ENOENT/);}finally{await rm(root,{recursive:true,force:true});}});

test('template vendoring includes license and README, excludes caches, and rejects symlink payloads',async()=>{
 const root=await mkdtemp(join(tmpdir(),'plugin-vendor-payload-'));
 const {fileURLToPath}=await import('node:url');const {spawnSync}=await import('node:child_process');
 const names=['plugin-protocol','plugin-sdk','plugin-host','plugin-codegen','plugin-cli'];
 try {
  // Contaminate isolated installed payloads, never the shared checkout used by npm pack.
  for(const name of names){
   const source=fileURLToPath(new URL('../../'+name+'/',import.meta.url));const destination=join(root,'node_modules/@napi-vm',name);
   await mkdir(destination,{recursive:true});const metadata=JSON.parse(await readFile(join(source,'package.json'),'utf8'));
   for(const file of [...metadata.files,'package.json','LICENSE','README.md'])await cp(join(source,file),join(destination,file),{recursive:true});
  }
  const payload=join(root,'node_modules/@napi-vm/plugin-cli/src');
  for(const name of ['target','.cache']){await mkdir(join(payload,name));await writeFile(join(payload,name,'fixture.txt'),'must not be vendored');}
  const entry=join(root,'node_modules/@napi-vm/plugin-cli/src/index.mjs');const project=join(root,'project');
  const created=spawnSync(process.execPath,[entry,'create',project,'--language','ts'],{cwd:root,encoding:'utf8',timeout:30000});assert.equal(created.status,0,created.stderr);
  for(const name of names){await access(join(project,'vendor',name,'LICENSE'));await access(join(project,'vendor',name,'README.md'));}
  for(const name of ['target','.cache'])await assert.rejects(access(join(project,'vendor/plugin-cli/src',name)),/ENOENT/);
  await writeFile(join(root,'outside'),'outside source');await symlink(join(root,'outside'),join(payload,'alias'),'file');
  const rejected=join(root,'symlink-project');const failed=spawnSync(process.execPath,[entry,'create',rejected,'--language','ts'],{cwd:root,encoding:'utf8',timeout:30000});
  assert.equal(failed.status,1);assert.match(failed.stderr,/Refusing symlink/);await assert.rejects(access(rejected),/ENOENT/);
 } finally {await rm(root,{recursive:true,force:true});}
});

test('CLI failures exit nonzero, write stderr, and preserve the JSON stdout channel',async()=>{
 const {spawnSync}=await import('node:child_process');const {fileURLToPath}=await import('node:url');
 const entry=fileURLToPath(new URL('../src/index.mjs',import.meta.url));
 for(const args of [['no-such-command'],['pack','.','--out'],['invoke','.','--interface','example.greeter','--method','greet','--input','{']]){
  const result=spawnSync(process.execPath,[entry,...args],{encoding:'utf8',timeout:10000});
  assert.equal(result.status,1,result.stderr);assert.equal(result.stdout,'');assert(result.stderr.length>0);
 }
});
