import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir,rm,symlink,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {main} from '../src/index.mjs';
import {pack,contained,prepareDevelopmentPackage,currentTarget} from '../src/pack.mjs';
const contract=JSON.parse(await readFile(new URL('../../../contracts/trusted-plugins/generated/greeter.contract.json',import.meta.url),'utf8'));
async function fixture(root){const dir=join(root,'source with spaces 🌍');await mkdir(join(dir,'dist'),{recursive:true});await mkdir(join(dir,'contracts'));await writeFile(join(dir,'dist/main.js'),'console.log("owned test fixture");\n');await writeFile(join(dir,'contracts/greeter.contract.json'),JSON.stringify(contract));await writeFile(join(dir,'plugin.json'),JSON.stringify({manifestVersion:2,execution:'trusted-process',id:'example.greeter',version:'0.1.0',protocol:{major:1,minMinor:0,maxMinor:0},provides:{'example.greeter':'1.0.0'},requiresHost:{},launch:{kind:'javascript',entry:'./dist/main.js',runtimes:['node'],preferredRuntime:'node',args:[]},assets:[],contracts:['./contracts/greeter.contract.json']}));return dir;}
test('create provides real templates and never overwrites',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-create-'));try{for(const language of ['ts','js','rust']){const destination=join(root,language);await main(['create',destination,'--language',language]);assert.equal((await stat(join(destination,'src',language==='rust'?'lib.rs':'plugin.'+language))).isFile(),true);if(language!=='rust'){const pkg=JSON.parse(await readFile(join(destination,'package.json'),'utf8'));assert.equal(pkg.dependencies['@napi-vm/plugin-sdk'],'file:vendor/plugin-sdk');assert.equal(pkg.devDependencies['@napi-vm/plugin-cli'],'file:vendor/plugin-cli');for(const name of ['plugin-protocol','plugin-sdk','plugin-host','plugin-codegen','plugin-cli']){const vendored=JSON.parse(await readFile(join(destination,'vendor',name,'package.json'),'utf8'));for(const [dependency,version]of Object.entries(vendored.dependencies??{}))if(dependency.startsWith('@napi-vm/'))assert.match(version,/^file:\.\.\//);await assert.rejects(stat(join(destination,'vendor',name,'node_modules')),/ENOENT/);}}await assert.rejects(main(['create',destination,'--language',language]),/overwrite/);}await assert.rejects(main(['create',join(root,'bad'),'--language','python']),/language/);}finally{await rm(root,{recursive:true,force:true});}});
test('pack creates relocatable complete inventory and detects tampering',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-pack-'));try{const dir=await fixture(root);const out=join(root,'package with spaces 🌍');const result=await pack(dir,out);assert.deepEqual(result.lock.artifact.availability,{built:true,distributed:false,tested:[]});assert.equal(result.lock.files['plugin.json'].length,64);await main(['validate',out]);await assert.rejects(pack(dir,out),/already exists/);await writeFile(join(out,'dist/main.js'),'tampered');await assert.rejects(main(['validate',out]),/integrity|checksum|mismatch/i);}finally{await rm(root,{recursive:true,force:true});}});
test('unsafe paths, outside symlinks, directory cycles and secrets fail before output',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-paths-'));try{const dir=await fixture(root);for(const path of ['../outside','dist/../main.js','C:\\outside','/etc/passwd','dist//main.js'])await assert.rejects(contained(dir,path),/Unsafe/);await writeFile(join(root,'outside'),'test');await symlink(join(root,'outside'),join(dir,'escape'));await assert.rejects(contained(dir,'escape'),/escapes/);const m=JSON.parse(await readFile(join(dir,'plugin.json'),'utf8'));m.assets=['.env'];await writeFile(join(dir,'.env'),'FIXTURE=not-a-secret');await writeFile(join(dir,'plugin.json'),JSON.stringify(m));await assert.rejects(pack(dir,join(root,'secrets')),/sensitive/);m.assets=['cycle'];await symlink(dir,join(dir,'cycle'));await writeFile(join(dir,'plugin.json'),JSON.stringify(m));await assert.rejects(pack(dir,join(root,'cycles')),/escapes|cycle|unsafe/i);}finally{await rm(root,{recursive:true,force:true});}});
test('CLI rejects missing option values and invalid JSON without loading',async()=>{await assert.rejects(main(['pack','.','--out']),/requires a value/);await assert.rejects(main(['invoke','.','--interface','example.greeter','--method','greet','--input','{']),SyntaxError);await assert.rejects(main(['no-such-command']),/Unknown command/);});
test('doctor validates runtime names before probing executables',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-doctor-'));try{const dir=await fixture(root);const path=join(dir,'plugin.json');const manifest=JSON.parse(await readFile(path,'utf8'));manifest.launch.runtimes=['/untrusted/not-a-runtime'];manifest.launch.preferredRuntime='/untrusted/not-a-runtime';await writeFile(path,JSON.stringify(manifest));const result=await main(['doctor',dir]);assert.equal(result.validation.valid,false);assert.deepEqual(result.runtimes,[]);}finally{await rm(root,{recursive:true,force:true});}});
test('CLI entrypoint runs through an npm-style bin symlink',async()=>{const {spawnSync}=await import('node:child_process');const {fileURLToPath}=await import('node:url');const root=await mkdtemp(join(tmpdir(),'plugin-bin-'));try{const bin=join(root,'napi-vm-plugin.mjs');await symlink(fileURLToPath(new URL('../src/index.mjs',import.meta.url)),bin,'file');const result=spawnSync(process.execPath,[bin,'help'],{encoding:'utf8',timeout:10000});assert.equal(result.status,0,result.stderr);assert.match(JSON.parse(result.stdout).help,/create <directory>/);}finally{await rm(root,{recursive:true,force:true});}});

test('native dev launch stages have verified inventories before host startup',async()=>{const root=await mkdtemp(join(tmpdir(),'plugin-native-dev-'));try{const directory=await fixture(root);const manifestPath=join(directory,'plugin.json');const manifest=JSON.parse(await readFile(manifestPath,'utf8'));const entry='dist/plugin'+(process.platform==='win32'?'.exe':'');await writeFile(join(directory,entry),'Controlled packaging fixture; not launched by this unit test.\n',{mode:0o755});manifest.profile='native-executable';manifest.launch={kind:'executable',entry,args:[],target:currentTarget()};await writeFile(manifestPath,JSON.stringify(manifest));const launchDirectory=await prepareDevelopmentPackage(directory,'executable');assert.notEqual(launchDirectory,directory);const lock=JSON.parse(await readFile(join(launchDirectory,'plugin.lock.json'),'utf8'));assert.equal(lock.artifact.profile,'native-executable');assert.equal(lock.files[entry].length,64);await main(['validate',launchDirectory]);assert.equal(await prepareDevelopmentPackage(directory,'js'),directory);await assert.rejects(prepareDevelopmentPackage(directory,'executable'),/already exists/);}finally{await rm(root,{recursive:true,force:true});}});
